version: '3.8'

services:
  evmaudit-web:
    build: .
    container_name: evmaudit_webapp
    platform: linux/amd64
    ports:
      - "8000:8000"
    volumes:
      # Montamos el directorio de resultados para que no se pierdan al apagar el contenedor
      - ./jsons/_uploads:/app/jsons/_uploads
      # Opcional: si quieres probar contratos locales sin subirlos por la web
      - ./contracts:/app/contracts
    environment:
      - ENV=production
    restart: unless-stopped