name: Docker Build and Test CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Job to build and push Docker image to GitHub Container Registry
  create-docker-image:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Login to GitHub Container Registry using the IMAGES_TFM_UNIR secret
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.IMAGES_TFM_UNIR }}

      # Build the Docker image and push it to GitHub Container Registry
      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/my-app:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  # Job to deploy the Docker image (this is just a placeholder, you can replace it with your actual deployment steps)
  deploy:
    needs: create-docker-image
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Docker image
        run: echo "Deploying Docker image... (replace this with your actual deployment steps)"
