name: Docker Build and Test CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Job to build and push Docker image to GitHub Container Registry
  create-docker-image:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: "recursive" # <── Esto descarga el repositorio 'evmaudit'

      # Login to GitHub Container Registry using the IMAGES_TFM_UNIR secret
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.IMAGES_TFM_UNIR }}

      # Build the Docker image and push it to GitHub Container Registry
      - name: Build and push Docker image
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')

          # Definimos los dos nombres de imagen (con SHA y con latest)
          IMAGE_SHA=ghcr.io/$REPO_LOWER/evmaudit:${{ github.sha }}
          IMAGE_LATEST=ghcr.io/$REPO_LOWER/evmaudit:latest

          # Construimos la imagen asignándole ambas etiquetas (-t)
          docker build --platform linux/amd64 \
            -t $IMAGE_SHA \
            -t $IMAGE_LATEST .

          # Subimos ambas etiquetas a GitHub Container Registry
          docker push $IMAGE_SHA
          docker push $IMAGE_LATEST

  # Job to deploy the Docker image (this is just a placeholder, you can replace it with your actual deployment steps)
  deploy:
    needs: create-docker-image
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Docker image
        run: echo "Deploying Docker image... (replace this with your actual deployment steps)"
